# Generated by Django 3.0.2 on 2020-02-14 15:43

import church.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='service',
            field=wagtail.core.fields.StreamField([('worship_section', wagtail.core.blocks.StructBlock([('worship_songs', wagtail.core.blocks.ListBlock(church.models.WorshipSongBlock, label='Worship song'))], name='Worship Section')), ('sermon_section', wagtail.core.blocks.StructBlock([], name='Sermon Section'))], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='bulletin',
            field=wagtail.core.fields.StreamField([('bulletin_section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('items', wagtail.core.blocks.ListBlock(church.models.BulletinItemBlock, label='Bulletin item'))], name='Bulletin Section'))]),
        ),
    ]
