# Generated by Django 3.0.2 on 2020-02-22 06:50

import church.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_auto_20200214_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='mediasec',
            field=wagtail.core.fields.StreamField([('media', church.models.ServiceMediaBlock(icon='media'))], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='service',
            field=wagtail.core.fields.StreamField([('worship_section', wagtail.core.blocks.StructBlock([('worship_songs', wagtail.core.blocks.ListBlock(church.models.WorshipSongBlock, label='Worship song'))], name='Worship Section')), ('announcements_section', wagtail.core.blocks.StructBlock([], name='Announcement Section')), ('sermon_section', wagtail.core.blocks.StructBlock([], name='Sermon Section'))]),
        ),
    ]
