# Generated by Django 3.0.3 on 2020-02-28 19:43

import church.models
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_servicepage_servicesindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='mediasec',
            field=wagtail.core.fields.StreamField([('media', church.models.ServiceMediaBlock(icon='media', required=False))]),
        ),
    ]
