# Generated by Django 3.0.2 on 2020-02-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_auto_20200214_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepagebulletinitem',
            name='contact_name',
            field=models.CharField(default='Zack Biel', max_length=250),
            preserve_default=False,
        ),
    ]
