# Generated by Django 3.0.3 on 2020-02-28 07:54

import church.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_auto_20200227_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='service',
            field=wagtail.core.fields.StreamField([('worship_section', wagtail.core.blocks.StructBlock([('worship_songs', wagtail.core.blocks.ListBlock(church.models.WorshipSongBlock, label='Worship song'))], name='Worship Section')), ('announcements_section', wagtail.core.blocks.StructBlock([], name='Announcement Section')), ('sermon_section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('speaker', wagtail.core.blocks.CharBlock()), ('slides_url', wagtail.core.blocks.CharBlock())], name='Sermon Section')), ('discussion_section', wagtail.core.blocks.StructBlock([('items', church.models.IDListBlock(church.models.DiscussionItemBlock, label='Discussion item'))], name='Discussion Section'))]),
        ),
    ]
