# Generated by Django 3.0.3 on 2020-03-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_personalstoriespage_prayerrequestspage_sundaygatheringspage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrayerRequest',
        ),
    ]
