# Generated by Django 3.0.4 on 2020-03-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('church', '0008_servicepage_prayer_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='mediasec',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service',
        ),
        migrations.DeleteModel(
            name='PrayerRequestsPage',
        ),
    ]
