# Generated by Django 3.0.4 on 2020-03-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_servicepage_stream_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='stream_link',
            field=models.URLField(default=''),
        ),
    ]
