# Generated by Django 3.0.4 on 2020-04-06 18:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('church', '0013_auto_20200328_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReadingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='Date')),
                ('video_link', models.URLField(blank=True, default='')),
                ('chat_enabled', models.BooleanField(default=True)),
                ('content', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='stream_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
