# Generated by Django 3.0.4 on 2020-04-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_auto_20200406_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='weekly_theme',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
