# Generated by Django 3.0.4 on 2020-04-13 03:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0016_servicepagedocumentlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreadingpage',
            name='chat_enabled',
        ),
        migrations.AddField(
            model_name='dailyreadingpage',
            name='reflection',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
