# Generated by Django 3.0.4 on 2020-04-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0019_servicepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_daily_email',
            field=models.BooleanField(default=False),
        ),
    ]
