# Generated by Django 3.0.4 on 2020-04-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0020_user_subscribe_daily_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='public_stream_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
