# Generated by Django 3.0.4 on 2020-04-24 01:58

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0022_basicpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='show_last_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='stream',
            field=wagtail.core.fields.StreamField([('offering', wagtail.core.blocks.StructBlock([], name='Offering Section'))], blank=True),
        ),
    ]
