version: '3.7'

# Unfortunately we can't extend prod.yml as the volumes
# will be combined rather than overridden.
# This file must be as similar as possible to prod.yml.

services:
  app:
    extends:
      file: common.yml
      service: app
    image: ghcr.io/crossroadsinajax/app:latest
    environment:
      - DD_ENV=staging
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata groups &&
             ddtrace-run daphne -b 0.0.0.0 -p 8000 crossroads.asgi:application"
    secrets:
      - django_secret
      - postmark_api_key
    volumes:
      - staticfiles:/app/static
      - /home/kyle/staging/db.sqlite3:/app/db.sqlite3
      - /home/kyle/staging/media:/app/media

  web:
    extends:
      file: common.yml
      service: web
    image: ghcr.io/crossroadsinajax/web:latest
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.prod
    # Outputs app.js to /static/
    # Defined in web/webpack.prod.js.
    command: yarn run build
    volumes:
      - staticfiles:/static

  nginx:
    extends:
      file: common.yml
      service: nginx
    image: ghcr.io/crossroadsinajax/nginx:latest
    build:
      context: ./docker/nginx_prod
      dockerfile: ./Dockerfile
    ports:
      - 8001:80
    volumes:
      - staticfiles:/static

  datadog:
    extends:
      file: common.yml
      service: datadog
    image: ghcr.io/crossroadsinajax/datadog-agent:latest
    environment:
      - DD_LOG_LEVEL=WARNING
      - DD_API_KEY_FILE=/run/secrets/datadog_api_key
    secrets:
      - datadog_api_key

volumes:
  staticfiles:

secrets:
  datadog_api_key:
    external: true
  django_secret:
    external: true
  postmark_api_key:
    external: true
