# Generated by Django 3.0.4 on 2020-03-21 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='kind',
            field=models.CharField(choices=[('PR', 'pr'), ('CHAT', 'chat')], default='CHAT', max_length=16),
        ),
    ]
