# Generated by Django 3.0.4 on 2020-03-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200321_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
