# Generated by Django 3.0.4 on 2020-03-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessagereact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='kind',
        ),
    ]
