# Generated by Django 3.0.4 on 2020-03-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chatmessage_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='chat.ChatMessage')),
            ],
        ),
    ]
