# Generated by Django 3.0.3 on 2020-03-04 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_visibility', models.CharField(choices=[('', 'Only you'), ('member', 'Only Crossroads members'), ('prayer_team', 'Only Crossroads prayer team members')], default='', max_length=32)),
                ('provided_name', models.CharField(default='', max_length=64)),
                ('body', models.CharField(max_length=16384)),
                ('state', models.CharField(choices=[('ACT', 'Active'), ('ANS', 'Answered')], default='ACT', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerRequestReact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacts', to='prayer.PrayerRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
